# Generated by Django 3.1.7 on 2022-11-26 04:27

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nId_person', models.CharField(max_length=100, verbose_name='รหัส')),
                ('cGender', models.CharField(blank=True, max_length=19, null=True, verbose_name='เพศ')),
                ('cFname', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('nAge', models.IntegerField(blank=True, null=True, verbose_name='อายุ')),
                ('cLevel', models.CharField(blank=True, max_length=100, null=True, verbose_name='ธรรมวุฒิ')),
                ('cEdu', models.CharField(blank=True, max_length=100, null=True, verbose_name='การศึกษา')),
                ('cCareer', models.CharField(blank=True, max_length=100, null=True, verbose_name='อาชีพ')),
                ('cRoom', models.CharField(blank=True, max_length=100, null=True, verbose_name='พุทธสถาน')),
                ('cRoom_c', models.CharField(blank=True, max_length=100, null=True, verbose_name='พุทธสถาน(จีน)')),
                ('cPro', models.CharField(blank=True, max_length=100, null=True, verbose_name='อ.ถ่ายทอดเบิกธรรม')),
                ('cPro_c', models.CharField(blank=True, max_length=100, null=True, verbose_name='อ.ถ่ายทอดเบิกธรรม(จีน)')),
                ('cDate_c', models.CharField(blank=True, max_length=100, null=True, verbose_name='วันรับธรรมะ(ภาษาจีน)')),
                ('cDate_dc', models.CharField(blank=True, max_length=100, null=True, verbose_name='วันรับธรรมะ(จีน)')),
                ('cTdate', models.CharField(blank=True, max_length=100, null=True, verbose_name='วันรับธรรมะ(ไทย)')),
                ('dDate', models.DateField(blank=True, null=True, verbose_name='วันรับธรรมะ')),
                ('cRec', models.CharField(blank=True, max_length=100, null=True, verbose_name='อ.แนะนำ')),
                ('cSup', models.CharField(blank=True, max_length=100, null=True, verbose_name='อ.รับรอง')),
                ('cAddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='ที่อยู่')),
                ('cMtel', models.CharField(blank=True, max_length=100, null=True, verbose_name='โทรศัพท์มือถือ')),
                ('cHtel', models.CharField(blank=True, max_length=100, null=True, verbose_name='โทรศัพท์บ้าน')),
                ('cName', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อจีน')),
                ('c3dd', models.CharField(blank=True, max_length=100, null=True)),
                ('c3dl', models.CharField(blank=True, max_length=100, null=True)),
                ('cMd', models.CharField(blank=True, max_length=100, null=True)),
                ('cMl', models.CharField(blank=True, max_length=100, null=True)),
                ('cSd', models.CharField(blank=True, max_length=100, null=True)),
                ('cSl', models.CharField(blank=True, max_length=100, null=True)),
                ('cJd', models.CharField(blank=True, max_length=100, null=True)),
                ('cJl', models.CharField(blank=True, max_length=100, null=True)),
                ('cPt1', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt2', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt3', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt4', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt5', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt6', models.CharField(blank=True, max_length=3, null=True)),
                ('cCd', models.CharField(blank=True, max_length=100, null=True)),
                ('cCl', models.CharField(blank=True, max_length=100, null=True)),
                ('cCp', models.CharField(blank=True, max_length=100, null=True)),
                ('cUd', models.CharField(blank=True, max_length=100, null=True)),
                ('cUl', models.CharField(blank=True, max_length=100, null=True)),
                ('cUp', models.CharField(blank=True, max_length=100, null=True)),
                ('cRd', models.CharField(blank=True, max_length=100, null=True)),
                ('cRl', models.CharField(blank=True, max_length=100, null=True)),
                ('cRp', models.CharField(blank=True, max_length=100, null=True)),
                ('cPd', models.CharField(blank=True, max_length=100, null=True)),
                ('cPl', models.CharField(blank=True, max_length=100, null=True)),
                ('cPp', models.CharField(blank=True, max_length=100, null=True)),
                ('cJvd', models.CharField(blank=True, max_length=100, null=True)),
                ('cJvl', models.CharField(blank=True, max_length=100, null=True)),
                ('cJvp', models.CharField(blank=True, max_length=100, null=True)),
                ('cTjd', models.CharField(blank=True, max_length=100, null=True)),
                ('cTjl', models.CharField(blank=True, max_length=100, null=True)),
                ('cTjp', models.CharField(blank=True, max_length=100, null=True)),
                ('cJcd', models.CharField(blank=True, max_length=100, null=True)),
                ('cJcl', models.CharField(blank=True, max_length=100, null=True)),
                ('cJcp', models.CharField(blank=True, max_length=100, null=True)),
                ('cPrd', models.CharField(blank=True, max_length=100, null=True)),
                ('cPrl', models.CharField(blank=True, max_length=100, null=True)),
                ('cPrp', models.CharField(blank=True, max_length=100, null=True)),
                ('cb3d', models.BooleanField(default=False)),
                ('cbM', models.BooleanField(default=False)),
                ('cbS', models.BooleanField(default=False)),
                ('cbJ', models.BooleanField(default=False)),
                ('cbJv', models.BooleanField(default=False)),
                ('cbJc', models.BooleanField(default=False)),
                ('cbReview', models.BooleanField(default=False)),
                ('cbAdv', models.BooleanField(default=False)),
                ('cbDd', models.BooleanField(default=False)),
                ('cDd', models.CharField(blank=True, max_length=100, null=True)),
                ('cJv_detail', models.TextField(blank=True, null=True)),
                ('cJc_detail', models.TextField(blank=True, null=True)),
                ('cReview_detail', models.TextField(blank=True, null=True)),
                ('cAdv_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bkk',
            fields=[
                ('tableall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.tableall')),
            ],
            bases=('app.tableall',),
        ),
        migrations.CreateModel(
            name='Nma',
            fields=[
                ('tableall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.tableall')),
            ],
            bases=('app.tableall',),
        ),
        migrations.CreateModel(
            name='Plk',
            fields=[
                ('tableall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.tableall')),
            ],
            bases=('app.tableall',),
        ),
        migrations.CreateModel(
            name='Skw',
            fields=[
                ('tableall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.tableall')),
            ],
            bases=('app.tableall',),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(default='Admin', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bkk1',
            fields=[
                ('bkk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.bkk')),
            ],
            bases=('app.bkk',),
        ),
        migrations.CreateModel(
            name='Nma1',
            fields=[
                ('nma_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.nma')),
            ],
            bases=('app.nma',),
        ),
        migrations.CreateModel(
            name='Plk1',
            fields=[
                ('plk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.plk')),
            ],
            bases=('app.plk',),
        ),
        migrations.CreateModel(
            name='Skw1',
            fields=[
                ('skw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw')),
            ],
            bases=('app.skw',),
        ),
        migrations.CreateModel(
            name='Skw3',
            fields=[
                ('skw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw')),
            ],
            bases=('app.skw',),
        ),
        migrations.CreateModel(
            name='Bkk101',
            fields=[
                ('bkk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.bkk1')),
            ],
            bases=('app.bkk1',),
        ),
        migrations.CreateModel(
            name='Bkk102',
            fields=[
                ('bkk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.bkk1')),
            ],
            bases=('app.bkk1',),
        ),
        migrations.CreateModel(
            name='Bkk103',
            fields=[
                ('bkk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.bkk1')),
            ],
            bases=('app.bkk1',),
        ),
        migrations.CreateModel(
            name='Bkk104',
            fields=[
                ('bkk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.bkk1')),
            ],
            bases=('app.bkk1',),
        ),
        migrations.CreateModel(
            name='Nma101',
            fields=[
                ('nma1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.nma1')),
            ],
            bases=('app.nma1',),
        ),
        migrations.CreateModel(
            name='Nma102',
            fields=[
                ('nma1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.nma1')),
            ],
            bases=('app.nma1',),
        ),
        migrations.CreateModel(
            name='Nma103',
            fields=[
                ('nma1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.nma1')),
            ],
            bases=('app.nma1',),
        ),
        migrations.CreateModel(
            name='Nma104',
            fields=[
                ('nma1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.nma1')),
            ],
            bases=('app.nma1',),
        ),
        migrations.CreateModel(
            name='Plk101',
            fields=[
                ('plk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.plk1')),
            ],
            bases=('app.plk1',),
        ),
        migrations.CreateModel(
            name='Plk102',
            fields=[
                ('plk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.plk1')),
            ],
            bases=('app.plk1',),
        ),
        migrations.CreateModel(
            name='Plk103',
            fields=[
                ('plk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.plk1')),
            ],
            bases=('app.plk1',),
        ),
        migrations.CreateModel(
            name='Plk104',
            fields=[
                ('plk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.plk1')),
            ],
            bases=('app.plk1',),
        ),
        migrations.CreateModel(
            name='Skw101',
            fields=[
                ('skw1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw1')),
            ],
            bases=('app.skw1',),
        ),
        migrations.CreateModel(
            name='Skw102',
            fields=[
                ('skw1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw1')),
            ],
            bases=('app.skw1',),
        ),
        migrations.CreateModel(
            name='Skw103',
            fields=[
                ('skw1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw1')),
            ],
            bases=('app.skw1',),
        ),
        migrations.CreateModel(
            name='Skw104',
            fields=[
                ('skw1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw1')),
            ],
            bases=('app.skw1',),
        ),
        migrations.CreateModel(
            name='Skw301',
            fields=[
                ('skw3_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw3')),
            ],
            bases=('app.skw3',),
        ),
        migrations.CreateModel(
            name='Skw302',
            fields=[
                ('skw3_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw3')),
            ],
            bases=('app.skw3',),
        ),
        migrations.CreateModel(
            name='Skw303',
            fields=[
                ('skw3_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw3')),
            ],
            bases=('app.skw3',),
        ),
        migrations.CreateModel(
            name='Skw304',
            fields=[
                ('skw3_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.skw3')),
            ],
            bases=('app.skw3',),
        ),
    ]
